[package]
name = "bitcoin_alert"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
dotenv = "0.15.0"
json = "0.12.4"
reqwest = {version = "0.12.15", features = ["blocking", "json"]}
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
